"""Local place catalogues and a cached, rate-limited geocoding client.

No radio transcripts, task bodies or coordinates generated by an LLM are sent to
the geocoder. All external searches share one queue/limiter in this process.
"""
from __future__ import annotations

import asyncio
import csv
import hashlib
import io
import json
import time
import unicodedata
from pathlib import Path
from urllib.parse import urlparse

import httpx

from .config import Settings
from .geography_models import (
    AreaInput, Bounds, MasterPlace, OperatingArea, PlaceCandidate, YOKOHAMA_AREA,
)
from .models import TaskRecord
from .storage import DataStore


YOKOHAMA_SOURCE = "https://www.city.yokohama.lg.jp/bousai-kyukyu-bohan/bousai-saigai/data/shiryodata/data/data.html"
YOKOHAMA_CSV = "https://www.city.yokohama.lg.jp/bousai-kyukyu-bohan/bousai-saigai/data/shiryodata/data/data.files/hinanjo.csv"
OSM_LICENSE = "https://www.openstreetmap.org/copyright"


def normalized(value: str) -> str:
    return "".join(unicodedata.normalize("NFKC", value).casefold().split())


def place_query(task: TaskRecord) -> str:
    if task.map_info is not None:
        return task.map_info.location.search_name.strip() if task.map_info.location else ""
    return (task.location or "").strip()


def query_key(task: TaskRecord) -> str:
    expression = task.map_info.location if task.map_info else None
    parts = [task.area.id if task.area else "", normalized(place_query(task))]
    parts.extend([
        normalized(expression.municipality or "") if expression else "",
        normalized(expression.district or "") if expression else "",
    ])
    return hashlib.sha256(json.dumps(parts, ensure_ascii=False).encode()).hexdigest()


def parse_yokohama_csv(payload: bytes) -> list[MasterPlace]:
    try:
        content = payload.decode("utf-8-sig")
    except UnicodeDecodeError:
        content = payload.decode("cp932")
    reader = csv.DictReader(io.StringIO(content))
    if not {"Name", "Address", "Lat", "Lon"}.issubset(reader.fieldnames or []):
        raise ValueError("横浜市の地点データに必要な列がありません")
    places = []
    for row in reader:
        if not row.get("Name") or not row.get("Lat") or not row.get("Lon"):
            continue
        name, address = row["Name"].strip(), row["Address"].strip()
        lat, lon = float(row["Lat"]), float(row["Lon"])
        if not YOKOHAMA_AREA.bounds.contains(lat, lon):
            continue
        digest = hashlib.sha256(f"{name}|{address}".encode()).hexdigest()[:20]
        aliases = [f"横浜市{name}", f"横浜市立{name}", f"神奈川県横浜市{name}"]
        if row.get("Kana"):
            aliases.append(row["Kana"].strip())
        if name.endswith(("小学校", "中学校")):
            aliases.extend([name + "避難所", "横浜市立" + name + "避難所"])
        places.append(MasterPlace(
            id=f"yokohama-{digest}", name=name, address=address,
            lat=lat, lon=lon, source="master", aliases=aliases,
            source_url=YOKOHAMA_SOURCE, license="横浜市 防災関連データ / CC BY 2.1 JP",
        ))
    if not places:
        raise ValueError("横浜市の有効な地点を読み込めませんでした")
    return places


class Geography:
    def __init__(self, settings: Settings, *, transport=None, clock=time.time, sleep=asyncio.sleep):
        self.settings = settings
        self.root = settings.data_dir / "geography"
        self.transport = transport
        self.clock, self.sleep = clock, sleep
        self._network_lock = asyncio.Lock()
        self._refresh_lock = asyncio.Lock()
        self.master: list[MasterPlace] = []
        self.cache: dict = {"entries": {}, "last_request_at": 0}
        self.confirmed: dict = {}
        self.catalog_status: dict = {"status": "ready", "count": 0, "error": None}
        self.diagnostics: list[str] = []

    def initialize(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        self.cache = self._load(self.root / "search-cache.json", self.cache)
        if not isinstance(self.cache.get("entries"), dict):
            self.cache = {"entries": {}, "last_request_at": 0}
        self.confirmed = self._load(self.root / "confirmed-cache.json", {})
        self._reload_master()

    def _load(self, path: Path, default):
        try:
            if path.exists():
                result = json.loads(path.read_text(encoding="utf-8"))
                if not isinstance(result, dict):
                    raise ValueError("JSON object expected")
                return result
        except (OSError, ValueError) as exc:
            self.diagnostics.append(f"{path.name}: {exc}")
        return default

    def _reload_master(self) -> None:
        resources = Path(__file__).parent / "resources"
        def read_places(path: Path) -> list[MasterPlace]:
            places = []
            payload = self._load(path, {})
            rows = payload.get("places", [])
            if not isinstance(rows, list):
                return places
            for row in rows:
                try:
                    places.append(MasterPlace.model_validate(row))
                except ValueError as exc:
                    self.diagnostics.append(f"{path.name}: {exc}")
            return places

        self.master = read_places(self.root / "yokohama-places.json")
        if not self.master:
            self.master = read_places(resources / "yokohama-places.json")
        for path in [resources / "yokohama-landmarks.json", self.root / "locations.json"]:
            self.master.extend(read_places(path))
        self.catalog_status["count"] = len(self.master)

    def config(self) -> dict:
        return {
            "tile_url": self.settings.tile_url,
            "tile_attribution": self.settings.tile_attribution,
            "geocoder_enabled": self.settings.geocoder_enabled,
            "catalog": self.catalog_status,
            "diagnostics": self.diagnostics,
            "default_area": YOKOHAMA_AREA.model_dump(mode="json"),
            "sources": [{"label": "横浜市 防災関連データ", "url": YOKOHAMA_SOURCE}],
        }

    @staticmethod
    def _candidate(place: MasterPlace) -> PlaceCandidate:
        return PlaceCandidate.model_validate(place.model_dump(exclude={"aliases"}))

    def local_candidates(self, task: TaskRecord) -> list[PlaceCandidate]:
        if not task.area:
            return []
        name = normalized(place_query(task))
        if not name or name in {"未確認", "不明"}:
            return []
        matches = []
        expression = task.map_info.location if task.map_info else None
        for place in self.master:
            if not task.area.bounds.contains(place.lat, place.lon):
                continue
            if name not in {normalized(value) for value in [place.name, *place.aliases]}:
                continue
            # Explicit municipality/district information must not be lost in matching.
            if expression and any(
                value and normalized(value) not in normalized(place.address + place.name)
                for value in (expression.municipality, expression.district)
            ):
                continue
            matches.append(self._candidate(place))
        return self._dedupe(matches)

    @staticmethod
    def _dedupe(places: list[PlaceCandidate]) -> list[PlaceCandidate]:
        result = {}
        for place in places:
            key = (normalized(place.name), round(place.lat, 5), round(place.lon, 5))
            result.setdefault(key, place)
        return list(result.values())[:20]

    def remember(self, task: TaskRecord) -> None:
        if task.area and task.position.selected and place_query(task):
            self.confirmed[query_key(task)] = task.position.selected.model_dump(mode="json")
            DataStore._write_json_atomic(self.root / "confirmed-cache.json", self.confirmed)

    async def resolve(self, task: TaskRecord) -> list[PlaceCandidate]:
        if not task.area or not place_query(task) or place_query(task) in {"未確認", "不明"}:
            return []
        local = self.local_candidates(task)
        if local:
            return local
        confirmed = self.confirmed.get(query_key(task))
        if confirmed:
            try:
                place = PlaceCandidate.model_validate(confirmed)
                if task.area.bounds.contains(place.lat, place.lon):
                    return [place]
            except ValueError:
                pass
        expression = task.map_info.location if task.map_info else None
        terms = [task.area.name, place_query(task)]
        if expression:
            terms.extend([expression.municipality or "", expression.district or ""])
        # No task action, people, resources, transcript, or free-form location detail.
        query = " ".join(dict.fromkeys(term for term in terms if term))
        return await self._search(query, task.area.bounds, area_search=False)

    async def search_areas(self, query: str) -> list[AreaInput]:
        if normalized(query) in {"横浜", "横浜市", "神奈川県横浜市"}:
            return [YOKOHAMA_AREA]
        places = await self._search(query.strip(), None, area_search=True)
        return [AreaInput(name=place.name, bounds=place.bounds) for place in places if place.bounds]

    async def _search(self, query: str, bounds: Bounds | None, *, area_search: bool) -> list[PlaceCandidate]:
        params = {"q": query, "format": "jsonv2", "limit": "5", "addressdetails": "1", "accept-language": "ja"}
        if bounds:
            params.update(viewbox=f"{bounds.west},{bounds.north},{bounds.east},{bounds.south}", bounded="1")
        if area_search:
            params.update(layer="address", featureType="settlement", countrycodes="jp")
        key = hashlib.sha256(json.dumps([self.settings.geocoder_url, params], sort_keys=True).encode()).hexdigest()
        # Cache reads are repeated inside the lock: simultaneous identical tasks share one request.
        async with self._network_lock:
            cached = self.cache["entries"].get(key)
            if cached and self.clock() - cached["at"] < (86400 * 30 if cached["results"] else 86400):
                return [PlaceCandidate.model_validate(value) for value in cached["results"]]
            if not self.settings.geocoder_enabled:
                raise RuntimeError("外部の地名検索は無効です。登録地点または手動指定を使用してください")
            parsed = urlparse(self.settings.geocoder_url)
            if parsed.scheme not in {"http", "https"} or not parsed.hostname:
                raise ValueError("地名検索URLが不正です")
            public = parsed.hostname.lower() == "nominatim.openstreetmap.org"
            if public and parsed.scheme != "https":
                raise ValueError("公開NominatimはHTTPSで指定してください")
            interval = max(15.0 if public else 0.0, self.settings.geocoder_interval_seconds)
            delay = interval - (self.clock() - float(self.cache.get("last_request_at", 0)))
            if delay > 0:
                await self.sleep(delay)
            self.cache["last_request_at"] = self.clock()
            DataStore._write_json_atomic(self.root / "search-cache.json", self.cache)
            async with httpx.AsyncClient(
                timeout=self.settings.geocoder_timeout_seconds, transport=self.transport,
                headers={"User-Agent": self.settings.geocoder_user_agent}, follow_redirects=False,
            ) as client:
                response = await client.get(self.settings.geocoder_url, params=params)
                if response.status_code == 429:
                    # Honour server cooldown; no automatic retry of failed tasks.
                    try:
                        retry_after = max(60, float(response.headers.get("Retry-After", "60")))
                    except ValueError:
                        retry_after = 60
                    self.cache["last_request_at"] = self.clock() + retry_after
                    DataStore._write_json_atomic(self.root / "search-cache.json", self.cache)
                response.raise_for_status()
                if len(response.content) > 1_048_576:
                    raise ValueError("地名検索の応答が大きすぎます")
                payload = response.json()
            if not isinstance(payload, list):
                raise ValueError("地名検索の応答形式が不正です")
            results = []
            for row in payload[:20]:
                try:
                    lat, lon = float(row["lat"]), float(row["lon"])
                    if bounds and not bounds.contains(lat, lon):
                        continue
                    bbox = row.get("boundingbox")
                    candidate_bounds = Bounds(south=bbox[0], north=bbox[1], west=bbox[2], east=bbox[3]) if bbox else None
                    osm_type, osm_id = row.get("osm_type"), row.get("osm_id")
                    source_url = f"https://www.openstreetmap.org/{osm_type}/{osm_id}" if osm_type in {"node", "way", "relation"} and str(osm_id).isdigit() else OSM_LICENSE
                    results.append(PlaceCandidate(
                        id=f"osm-{osm_type}-{osm_id}" if osm_id else f"search-{row['place_id']}",
                        name=row.get("name") or row["display_name"], address=row.get("display_name", ""),
                        lat=lat, lon=lon, bounds=candidate_bounds, source="nominatim",
                        source_url=source_url, license="© OpenStreetMap contributors / ODbL",
                    ))
                except (KeyError, TypeError, ValueError, IndexError):
                    continue
            if payload and not results and bounds is None:
                raise ValueError("地名検索から有効な座標を取得できませんでした")
            results = self._dedupe(results)
            self.cache["entries"][key] = {"at": self.clock(), "results": [value.model_dump(mode="json") for value in results]}
            DataStore._write_json_atomic(self.root / "search-cache.json", self.cache)
            return results

    async def refresh_catalog(self, area: OperatingArea) -> None:
        if not self.settings.refresh_places or "横浜" not in area.name:
            return
        async with self._refresh_lock:
            path = self.root / "catalog-refresh.json"
            metadata = self._load(path, {})
            if self.clock() - metadata.get("checked_at", 0) < 86400:
                return
            metadata["checked_at"] = self.clock()
            DataStore._write_json_atomic(path, metadata)
            self.catalog_status.update(status="loading", error=None)
            headers = {"User-Agent": self.settings.geocoder_user_agent}
            if metadata.get("etag"):
                headers["If-None-Match"] = metadata["etag"]
            if metadata.get("last_modified"):
                headers["If-Modified-Since"] = metadata["last_modified"]
            try:
                async with httpx.AsyncClient(timeout=15, transport=self.transport, follow_redirects=True) as client:
                    response = await client.get(YOKOHAMA_CSV, headers=headers)
                if response.status_code != 304:
                    response.raise_for_status()
                    if len(response.content) > 5_000_000:
                        raise ValueError("地点一覧が大きすぎます")
                    places = parse_yokohama_csv(response.content)
                    DataStore._write_json_atomic(self.root / "yokohama-places.json", {
                        "source_url": YOKOHAMA_SOURCE, "fetched_at": self.clock(),
                        "places": [place.model_dump(mode="json") for place in places],
                    })
                    metadata.update(etag=response.headers.get("etag"), last_modified=response.headers.get("last-modified"))
                    DataStore._write_json_atomic(path, metadata)
                    self._reload_master()
                self.catalog_status.update(status="ready", error=None)
            except Exception as exc:
                self.catalog_status.update(status="cached", error=f"地点一覧の更新に失敗しました。保存済み地点を使用します: {exc}")
