/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles */
        get: operations["profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Create */
        post: operations["create_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regions */
        get: operations["regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Locations */
        get: operations["run_locations_api_runs__run_id__locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/recording/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Recording */
        post: operations["start_recording_api_runs__run_id__recording_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/recording/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Recording */
        post: operations["stop_recording_api_runs__run_id__recording_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/communications/{comm_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct */
        post: operations["correct_api_runs__run_id__communications__comm_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/communications/{comm_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_runs__run_id__communications__comm_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_runs__run_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/communications/{comm_id}/display-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Display Metric */
        post: operations["display_metric_api_runs__run_id__communications__comm_id__display_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Task */
        put: operations["edit_task_api_runs__run_id__tasks__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks/{task_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_api_runs__run_id__tasks__task_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks/{task_id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Location */
        post: operations["location_api_runs__run_id__tasks__task_id__location_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/tasks/{task_id}/interpretation-location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interpretation Location */
        post: operations["interpretation_location_api_runs__run_id__tasks__task_id__interpretation_location_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/audio/{comm_id}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio */
        get: operations["audio_api_runs__run_id__audio__comm_id___variant__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovedLocationInterpretation */
        ApprovedLocationInterpretation: {
            /** Communication Id */
            communication_id: string;
            /** Revision */
            revision: number;
            /** Interpretation Index */
            interpretation_index: number;
            /** Possible Meaning */
            possible_meaning: string;
            /** Original Expression */
            original_expression: string;
            evidence: components["schemas"]["Evidence"];
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "road_blocked" | "water" | "rescue" | "injury" | "medical" | "fire" | "flood" | "building_damage" | "communication" | "missing_person" | "sanitation" | "supplies" | "evacuation" | "power" | "other";
        /** Communication */
        Communication: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Received At */
            received_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /**
             * Original Text
             * @default
             */
            original_text: string;
            /** Corrections */
            corrections: components["schemas"]["Correction"][];
            /** Original Audio */
            original_audio: string | null;
            /** Recognition Audio */
            recognition_audio: string | null;
            /**
             * Transcription Status
             * @default queued
             * @enum {string}
             */
            transcription_status: "recording" | "queued" | "running" | "done" | "failed" | "interrupted";
            /**
             * Extraction Status
             * @default waiting
             * @enum {string}
             */
            extraction_status: "waiting" | "running" | "done" | "failed";
            extraction: components["schemas"]["Extraction"] | null;
            /** Extraction Revision */
            extraction_revision: number | null;
            /** Extraction Attempts */
            extraction_attempts: {
                [key: string]: unknown;
            }[];
            /** Error */
            error: string | null;
            /** Metrics */
            metrics: {
                [key: string]: number | string;
            };
        };
        /** ConfirmInterpretationLocation */
        ConfirmInterpretationLocation: {
            /** Communication Id */
            communication_id: string;
            /** Revision */
            revision: number;
            /** Interpretation Index */
            interpretation_index: number;
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            /** Location Id */
            location_id: string;
        };
        /** ConfirmLocation */
        ConfirmLocation: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            /** Candidate Id */
            candidate_id?: string | null;
            manual?: components["schemas"]["Location-Input"] | null;
        };
        /** CorrectRequest */
        CorrectRequest: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            /** Text */
            text: string;
        };
        /** Correction */
        Correction: {
            /** Revision */
            revision: number;
            /** Text */
            text: string;
            /** Actor */
            actor: string;
            /** At */
            at: string;
        };
        /** DisplayMetric */
        DisplayMetric: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "final" | "subtitle";
            /** Displayed At Epoch */
            displayed_at_epoch: number;
            /** Captured At Epoch */
            captured_at_epoch?: number | null;
        };
        /** Evidence */
        Evidence: {
            /** Communication Id */
            communication_id: string;
            /** Revision */
            revision: number;
            /** Quote */
            quote: string;
        };
        /** ExtractedTask */
        ExtractedTask: {
            kind: components["schemas"]["Kind"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            place: components["schemas"]["PlaceExpression"] | null;
            /** Map Categories */
            map_categories: components["schemas"]["Category"][];
            /** Category Evidence */
            category_evidence: components["schemas"]["Evidence"][];
            /** Quantities */
            quantities: components["schemas"]["Quantity"][];
            /** Assignee */
            assignee: string | null;
            /** Deadline */
            deadline: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Related Task Ids */
            related_task_ids: string[];
            /** Uncertainties */
            uncertainties: string[];
        };
        /** Extraction */
        Extraction: {
            /** Sender */
            sender: string | null;
            /** Recipient */
            recipient: string | null;
            /** Situation */
            situation: string | null;
            /** People */
            people: components["schemas"]["Quantity"][];
            /** Phonetic Interpretations */
            phonetic_interpretations: components["schemas"]["PhoneticInterpretation"][];
            /** Transcript Interpretations */
            transcript_interpretations: components["schemas"]["TranscriptInterpretation"][];
            /** Tasks */
            tasks: components["schemas"]["ExtractedTask"][];
            /** Notices */
            notices: components["schemas"]["Notice"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /** Id */
            id: string;
            /** At */
            at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target Id */
            target_id: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
        };
        /** InterpretationLocationOption */
        InterpretationLocationOption: {
            /** Communication Id */
            communication_id: string;
            /** Revision */
            revision: number;
            /** Interpretation Index */
            interpretation_index: number;
            /** Task Id */
            task_id: string;
            /** Task Version */
            task_version: number;
            location: components["schemas"]["Location-Output"];
        };
        /**
         * Kind
         * @enum {string}
         */
        Kind: "request" | "situation_confirmation";
        /** Location */
        "Location-Input": {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Municipality */
            municipality: string;
            /** Aliases */
            aliases?: string[];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Precision
             * @default representative
             * @enum {string}
             */
            precision: "representative" | "specific";
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Source */
            source: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Checked At
             * @default
             */
            checked_at: string;
        };
        /** Location */
        "Location-Output": {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Municipality */
            municipality: string;
            /** Aliases */
            aliases: string[];
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Precision
             * @default representative
             * @enum {string}
             */
            precision: "representative" | "specific";
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Source */
            source: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Checked At
             * @default
             */
            checked_at: string;
        };
        /** LocationState */
        LocationState: {
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "unresolved" | "candidates" | "confirmed";
            /** Candidates */
            candidates: components["schemas"]["Location-Output"][];
            confirmed: components["schemas"]["Location-Output"] | null;
            /** Confirmed By */
            confirmed_by: string | null;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Reason */
            reason: string | null;
            interpretation: components["schemas"]["ApprovedLocationInterpretation"] | null;
        };
        /** Notice */
        Notice: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "uncertain" | "duplicate" | "completion" | "negation" | "contradiction";
            /** Text */
            text: string;
            /** Related Task Ids */
            related_task_ids: string[];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** PhoneticInterpretation */
        PhoneticInterpretation: {
            /** Original */
            original: string;
            /** Characters */
            characters: string[];
            /** Interpreted */
            interpreted: string | null;
            evidence: components["schemas"]["Evidence"];
        };
        /** PlaceExpression */
        PlaceExpression: {
            /**
             * Expression
             * @description 交信内で明示された地名・施設の固有名を省略せず、入口等の詳細地点と合わせた表現。
             */
            expression: string;
            /**
             * Search Name
             * @description 原文で明示された固有名を含む地名・施設名の全体。単に『公園』『集会所』のような施設種別に短縮しない。
             */
            search_name: string;
            /** Municipality */
            municipality: string | null;
            /** Detail */
            detail: string | null;
        };
        /** Profile */
        Profile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Training */
            training: boolean;
            /** External Geocoding */
            external_geocoding: boolean;
            /** Locations */
            locations: components["schemas"]["Location-Output"][];
        };
        /** Quantity */
        Quantity: {
            /** Value */
            value: number | null;
            /** Unit */
            unit: string | null;
            /** Description */
            description: string;
        };
        /** RecordingStart */
        RecordingStart: {
            /** Device */
            device?: number | null;
            /**
             * Manual Mode
             * @default false
             */
            manual_mode: boolean;
        };
        /** Region */
        "Region-Input": {
            /** Prefecture */
            prefecture: string;
            /**
             * Municipality
             * @default
             */
            municipality: string;
        };
        /** Region */
        "Region-Output": {
            /** Prefecture */
            prefecture: string;
            /**
             * Municipality
             * @default
             */
            municipality: string;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Demo Profile Id */
            demo_profile_id: string;
            /** Title */
            title: string;
            region: components["schemas"]["Region-Output"] | null;
            /** Created At */
            created_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Communications */
            communications: {
                [key: string]: components["schemas"]["Communication"];
            };
            /** Tasks */
            tasks: {
                [key: string]: components["schemas"]["Task"];
            };
            /** History */
            history: components["schemas"]["History"][];
        };
        /** RunCreate */
        RunCreate: {
            /** Demo Profile Id */
            demo_profile_id: string;
            /**
             * Title
             * @default
             */
            title: string;
            region?: components["schemas"]["Region-Input"] | null;
        };
        /** RunView */
        RunView: {
            /** Id */
            id: string;
            /** Demo Profile Id */
            demo_profile_id: string;
            /** Title */
            title: string;
            region: components["schemas"]["Region-Output"] | null;
            /** Created At */
            created_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Communications */
            communications: {
                [key: string]: components["schemas"]["Communication"];
            };
            /** Tasks */
            tasks: {
                [key: string]: components["schemas"]["Task"];
            };
            /** History */
            history: components["schemas"]["History"][];
            /** Interpretation Locations */
            interpretation_locations: components["schemas"]["InterpretationLocationOption"][];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "candidate" | "unhandled" | "completed" | "discarded";
        /** Task */
        Task: {
            kind: components["schemas"]["Kind"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            place: components["schemas"]["PlaceExpression"] | null;
            /** Map Categories */
            map_categories: components["schemas"]["Category"][];
            /** Category Evidence */
            category_evidence: components["schemas"]["Evidence"][];
            /** Quantities */
            quantities: components["schemas"]["Quantity"][];
            /** Assignee */
            assignee: string | null;
            /** Deadline */
            deadline: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Related Task Ids */
            related_task_ids: string[];
            /** Uncertainties */
            uncertainties: string[];
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** @default candidate */
            status: components["schemas"]["Status"];
            /**
             * Origin
             * @enum {string}
             */
            origin: "ai" | "manual";
            /** Manual Reason */
            manual_reason: string | null;
            /** Created At */
            created_at: string;
            location: components["schemas"]["LocationState"];
            /** Notices */
            notices: components["schemas"]["Notice"][];
        };
        /** TaskCreate */
        TaskCreate: {
            kind: components["schemas"]["Kind"];
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            place?: components["schemas"]["PlaceExpression"] | null;
            /** Map Categories */
            map_categories?: components["schemas"]["Category"][];
            /** Quantities */
            quantities?: components["schemas"]["Quantity"][];
            /** Assignee */
            assignee?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Related Task Ids */
            related_task_ids?: string[];
            /** Uncertainties */
            uncertainties?: string[];
            /** Manual Reason */
            manual_reason: string;
            /** Actor */
            actor: string;
        };
        /** TaskEdit */
        TaskEdit: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            kind: components["schemas"]["Kind"];
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            place?: components["schemas"]["PlaceExpression"] | null;
            /** Map Categories */
            map_categories?: components["schemas"]["Category"][];
            /** Quantities */
            quantities?: components["schemas"]["Quantity"][];
            /** Assignee */
            assignee?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Related Task Ids */
            related_task_ids?: string[];
            /** Uncertainties */
            uncertainties?: string[];
            /** Manual Reason */
            manual_reason: string;
        };
        /** TranscriptInterpretation */
        TranscriptInterpretation: {
            /** Possible Meaning */
            possible_meaning: string | null;
            /** Reason */
            reason: string;
            evidence: components["schemas"]["Evidence"];
        };
        /** TransitionRequest */
        TransitionRequest: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
            status: components["schemas"]["Status"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Versioned */
        Versioned: {
            /** Expected Version */
            expected_version: number;
            /** Actor */
            actor: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regions_api_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_locations_api_runs__run_id__locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_recording_api_runs__run_id__recording_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordingStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_recording_api_runs__run_id__recording_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_api_runs__run_id__communications__comm_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                comm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_runs__run_id__communications__comm_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                comm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Versioned"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_runs__run_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    display_metric_api_runs__run_id__communications__comm_id__display_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                comm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayMetric"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_task_api_runs__run_id__tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_api_runs__run_id__tasks__task_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_api_runs__run_id__tasks__task_id__location_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmLocation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpretation_location_api_runs__run_id__tasks__task_id__interpretation_location_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmInterpretationLocation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audio_api_runs__run_id__audio__comm_id___variant__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                comm_id: string;
                variant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
